version: "3"

networks:
  backend:

services: 

    php:
      build: ./php
      volumes:
        - ../:/var/www
      expose:
        - "9000"
      networks:
        - backend
    
    nginx:
      build: ./nginx
      volumes: 
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./nginx/log:/var/log/nginx
        - ../:/var/www
      ports:
        - "80:80"
        - "443:443"
      networks:
        - backend
    
    mysql:
      build: ./mysql
      environment:
        - MYSQL_DATABASE=default
        - MYSQL_ROOT_PASSWORD=root
        - TZ=Asia/Shanghai
      volumes: 
        - "~/.mingdock/mysql:/var/lib/mysql"
      ports:
        - "3306:3306"
      networks: 
        - backend

    redis:
      build: ./redis
      volumes:
        - "~/.mingdock/redis:/data"
      ports:
        - "6379:6379"
      networks: 
        - backend

    rabbitmq:
      build: ./rabbitmq
      ports:
        - "5672:5672"
        - "15672:15672"
        - "15671:15671"
      privileged: true
      environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
      volumes:
        - ~/.mingdock/rabbitmq:/var/lib/rabbitmq
      networks:
        - backend


    es:
      image: elasticsearch:7.13.2
      volumes:
        - ~/.mingdock/es/data:/usr/share/elasticsearch/data
      environment:
        - cluster.name=mingdock-cluster
        - node.name=mingdock-node
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - cluster.initial_master_nodes=mingdock-node
      ulimits:
        memlock:
          soft: -1
          hard: -1
        nofile:
          soft: 65536
          hard: 65536
      ports:
        - "9200:9200"
        - "9300:9300"
      networks:
        - backend

### MariaDB ##############################################
    mariadb:
      build:
        context: ./mariadb
        args:
          - http_proxy
          - https_proxy
          - no_proxy
      volumes:
        - ~/.mingdock/mariadb:/var/lib/mysql
        - ./mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      ports:
        - "3306:3306"
      environment:
        - TZ=UTC
        - MYSQL_DATABASE=default
        - MYSQL_USER=default
        - MYSQL_PASSWORD=secret
        - MYSQL_ROOT_PASSWORD=root
      networks:
        - backend
